update al-hello, add polybar launch script and merge menu switcher scripts

diff --git a/stable/al-hello b/stable/al-hello
--- a/stable/al-hello
+++ b/stable/al-hello
@@ -122,7 +122,6 @@ no="n"
 
 # colours
 b='\E[1;34m'
-b_nobold='\E[34m'
 red='\E[1;31m'
 g='\E[1;32m'
 y='\E[1;33m'
@@ -134,11 +133,11 @@ clear; echo -e "\n\n\n${b}                               _   _ _____ _     _    
                               | |_| |  _| | |   | |  | | | |
                               |  _  | |___| |___| |__| |_| |
                               |_| |_|_____|_____|_____\___/ \n${reg}"
-echo -e "                          Hi${b_nobold} ${USER} ${reg}, Welcome to ArchLabs Linux! ${b_nobold}:)${reg}\n"
+echo -e "                          Hi${b} ${USER} ${reg}, Welcome to ArchLabs Linux! ${b}:)${reg}\n"
 draw_box $R $C $H $W $col; sleep 1; read -n1 -rsp $'\n      Press Any Key to Continue...'
 clear
 
-printf "\n\n  Would you like to update the system & mirrorlist? (recommended) [y/n]: "
+printf "\n\n  Would you like to update the system & mirrorlist? (recommended) [Y/n]: "
 read -r upd
 
 if ! [ "${upd,,}" = "${no,,}" ]; then
@@ -150,7 +149,7 @@ if ! [ "${upd,,}" = "${no,,}" ]; then
   clear
   sudo pacman -Syyu --noconfirm
 
-  clear; echo -e "\n  You can refresh the mirrorlist anytime with the alias ${b}upmirrors${reg}\n"
+  clear; echo -e "\n  You can refresh the mirrorlist anytime with the alias ${red}upmirrors${reg}\n"
   sleep 1; read -n1 -rsp $'\n  Press Any Key to Continue...'
 fi
 
@@ -158,6 +157,9 @@ fi
 
 # if not a vm remove virtual utils
 if [ -z "${VM}" ]; then
+  echo -e "${g}Not running in a virtual environment...${reg}\n\n
+Removing Virtualbox Geust Modules & Utils"
+  sleep 1
   if [ -e /etc/xdg/autostart/vboxclient.desktop ]; then
     sudo rm -f /etc/xdg/autostart/vboxclient.desktop
   fi
@@ -179,11 +181,11 @@ if free | awk '/^Swap:/ {exit !$2}'; then
   sleep 1.5
 
 else
-  clear; printf "\n  Would you like to setup a swapfile? (required for suspend or sleep) [y/n]: "
+  clear; printf "\n  Would you like to setup a swapfile? (required for suspend or sleep) [y/N]: "
   read -r swp
 
   if [ "${swp,,}" = "${yes,,}" ]; then
-    clear; printf "\n  Set a custom size? (defaults to size of system RAM) [y/n]: "
+    clear; printf "\n  Set a custom size? (defaults to size of system RAM) [y/N]: "
     read -r cswp
 
     if [ "${cswp,,}" = "${yes,,}" ]; then
@@ -195,10 +197,15 @@ else
 fi
 
 
+# Nvidia Drivers
+if ! [ -z "${NV}" ]; then
+  clear; printf "\n  ${g}Nvidia Graphics Detected.${reg}\n\n  Want nvidia drivers installed?  [y/N]: "
+  read -r nvd
+fi
 
 
 # window manager and session
-clear; printf "\n  Pick from additional Window Managers or Desktop Environments?  [y/n]: "
+clear; printf "\n  Pick from additional Window Managers or Desktop Environments?  [Y/n]: "
 read -r desktop
 if ! [ "${desktop,,}" = "${no,,}" ]; then
   clear; printf "\n  Available\n
@@ -207,19 +214,19 @@ if ! [ "${desktop,,}" = "${no,,}" ]; then
 
   if [[ $wm == *1* ]] || [[ $wm == *2* ]] || [[ $wm == *3* ]] || [[ $wm == *4* ]]; then
     if [[ $wm == *1* ]]; then
-      clear; printf "\n  Want XFCE to be your login session?  [y/n]: "
+      clear; printf "\n  Want XFCE to be your login session?  [y/N]: "
       read -r xfses
     fi
 
     if [[ $wm == *2* ]]; then
       if ! [ "${xfses,,}" = "${yes,,}" ]; then
-        clear; printf "\n  Want i3 to be your login session?  [y/n]: "
+        clear; printf "\n  Want i3 to be your login session?  [y/N]: "
         read -r i3ses
       fi
     fi
 
     if [ "${xfses,,}" = "${yes,,}" ] || [ "${i3ses,,}" = "${yes,,}" ]; then
-      clear; printf "\n  ${red}Remove Openbox${reg}?  [y/n]: "
+      clear; printf "\n  ${red}Remove Openbox${reg}?  [y/N]: "
       read -r rmob
     fi
   fi
@@ -232,14 +239,14 @@ read -r dock
 
 
 
-clear; printf "\n  Select Applications to Install?  [y/n]: "
+clear; printf "\n  Select Applications to Install?  [Y/n]: "
 read -r defaults
 
 if ! [ "${defaults,,}" = "${no,,}" ]; then
 
-  clear; echo -e "\n\n  During the following you will be asked to pick applications you like,
+  clear; echo -e "\n  During the following you will be asked to pick applications you like,
   just enter the corresponding number of the application(s) you want installed
-  (${red}unless told otherwise any combination of choices can be made${reg})"
+  (${red}any combination of available apps can be picked${reg})"
 
   sleep 2
   read -n1 -rsp $'\n\n  Press Any Key to Continue...'
@@ -250,14 +257,14 @@ if ! [ "${defaults,,}" = "${no,,}" ]; then
   read -r bwsr
   if [[ $bwsr == *1* ]] || [[ $bwsr == *2* ]] || [[ $bwsr == *3* ]]; then
     if [[ $bwsr == *1* ]] || [[ $bwsr == *2* ]]; then
-      clear; printf "\n  Install google talk plugin?  [y/n]: "
+      clear; printf "\n  Install google talk plugin?  [y/N]: "
       read -r tlk
     fi
 
-    clear; printf "\n  Uninstall Firefox?  [y/n]: "
+    clear; printf "\n  Uninstall Firefox?  [y/N]: "
     read -r remove_firefox
     if ! [[ $bwsr == "1" ]] || [ "${remove_firefox,,}" = "${no,,}" ]; then
-      clear; printf "\n  Install flash plugin?  [y/n]: "
+      clear; printf "\n  Install flash plugin?  [y/N]: "
       read -r flsh
     fi
 
@@ -266,7 +273,7 @@ if ! [ "${defaults,,}" = "${no,,}" ]; then
     read -n1 -rsp $'  Press Any Key to continue...\n'
 
   else
-    clear; printf "\n  Install flash plugin?  [y/n]: "
+    clear; printf "\n  Install flash plugin?  [y/N]: "
     read -r flsh
   fi
 
@@ -276,22 +283,22 @@ if ! [ "${defaults,,}" = "${no,,}" ]; then
   1${red})${reg}Atom  2${red})${reg}Sublime  3${red})${reg}Mousepad\n\n\n: "
     read -r edit
   else
-    clear; printf "\n  Text Editors (Geany and Mousepad are default)\n
+    clear; printf "\n  Text Editors (Geany & Mousepad are default for XFCE)\n
   1${red})${reg}Atom  2${red})${reg}Sublime\n\n\n: "
     read -r edit
   fi
   if [[ $edit == *1* ]] || [[ $edit == *2* ]] || [[ $edit == *3* ]]; then
-    clear; printf "\n  Uninstall Geany?  [y/n]: "
+    clear; printf "\n  Uninstall Geany?  [y/N]: "
     read -r redit
   fi
 
 
   if ! [[ $wm == *1* ]]; then
-    clear; printf "\n  Terminal Emulators (Termite is the default)\n
+    clear; printf "\n  Terminal Emulators (Termite is default)\n
   1${red})${reg}Tilix  2${red})${reg}Terminator  3${red})${reg}Urxvt  4${red})${reg}Tilda  5${red})${reg}Xfce4 terminal\n\n\n: "
     read -r term
   else
-    clear; printf "\n  Terminal Emulators (Termite is the default)\n
+    clear; printf "\n  Terminal Emulators (Termite & XFCE4 Terminal are default)\n
   1${red})${reg}Tilix  2${red})${reg}Terminator  3${red})${reg}Urxvt  4${red})${reg}Tilda\n\n\n: "
     read -r term
   fi
@@ -305,11 +312,11 @@ if ! [ "${defaults,,}" = "${no,,}" ]; then
   1${red})${reg}Spotify  2${red})${reg}Nicotine+  3${red})${reg}Lollypop  4${red})${reg}Rythmbox  5${red})${reg}Clementine\n\n\n: "
   read -r musc
   if [[ $musc == *3* ]] || [[ $musc == *4* ]] || [[ $musc == *5* ]]; then
-    clear; printf "\n  Uninstall Audacious?  [y/n]: "
+    clear; printf "\n  Uninstall Audacious?  [y/N]: "
     read -r rmusc
   fi
 
-  clear; printf "\n  MPV is ArchLabs Default Video Player, install VLC instead? (120M) [y/n]: "
+  clear; printf "\n  MPV is ArchLabs Default Video Player, install VLC instead? (120M) [y/N]: "
   read -r vlc
 
   # if openbox wasnt removed and not using xfce we can change file manager
@@ -318,7 +325,7 @@ if ! [ "${defaults,,}" = "${no,,}" ]; then
     read -r file
     if ! [[ $wm == *1* ]]; then
       if [[ $file == *1* ]] || [[ $file == *2* ]] || [[ $file == *3* ]]; then
-        clear; printf "\n  Uninstall Thunar?  [y/n]: "
+        clear; printf "\n  Uninstall Thunar?  [y/N]: "
         read -r rmfile
       fi
     fi
@@ -369,55 +376,54 @@ if ! [ "${defaults,,}" = "${no,,}" ]; then
   1${red})${reg}Xfburn  2${red})${reg}Simpleburn  3${red})${reg}K3b\n\n\n: "
     read -r brn
 
-    clear; printf "\n  XFCE notifications?  [y/n]: "
+    clear; printf "\n  XFCE notifications?  [y/N]: "
     read -r notify
 
-    clear; printf "\n  XFCE Power Manager?  [y/n]: "
+    clear; printf "\n  XFCE Power Manager?  [y/N]: "
     read -r pwr
 
     # installing pamac if XFCE was chosen regardless
-    clear; printf "\n  Pamac Package Manager? (default is Pacli) [y/n]: "
+    clear; printf "\n  Pamac Package Manager? (default is Pacli) [y/N]: "
     read -r pac
   fi
 
-  clear; printf "\n  Gnome Disk Utility & System Monitor  [y/n]: "
+  clear; printf "\n  Gnome Disk Utility & System Monitor  [y/N]: "
   read -r gnm
 
-  clear; printf "\n  Catfish File Search  [y/n]: "
+  clear; printf "\n  Catfish File Search  [y/N]: "
   read -r sch
 
-  clear; printf "\n  Steam  [y/n]: "
+  clear; printf "\n  Steam  [y/N]: "
   read -r steam
 
-  clear; printf "\n  Dropbox  [y/n]: "
+  clear; printf "\n  Dropbox  [y/N]: "
   read -r dbox
 
-  clear; printf "\n  Some of our favorite fonts?  [y/n]: "
+  clear; printf "\n  Some of our favorite fonts?  [y/N]: "
   read -r fnt
 
-  clear; printf "\n  Additional icon patched fonts? (260M) [y/n]: "
+  clear; printf "\n  Additional icon patched fonts? (260M) [y/N]: "
   read -r nfnt
 
-  clear; printf "\n  Install oomox for making GTK themes?  [y/n]: "
+  clear; printf "\n  Install oomox for making GTK themes?  [y/N]: "
   read -r omox
 fi
 # end of default app selection
 
 
-
-
 clear; echo -e "${g}#######################################################################################
-#######                           Starting Install                              #######
+#######                 Installing Packages Needed for Building                 #######
 #######################################################################################${reg}"
-sleep 1; clear
-
-
+sleep 1
 sudo pacman -S base-devel --needed --noconfirm
 
 
 # if openbox wasnt removed
 if ! [ "${rmob,,}" = "${yes,,}" ]; then
 
+  clear; echo -e "${g}#######################################################################################
+#######               Setting up Menu Switcher & Obmenu Generator               #######
+#######################################################################################${reg}"
   # Setup menu generator and switcher scripts
   if ! (pacman -Q obmenu-generator perl-data-dump gtk2-perl perl-linux-desktopfiles) > /dev/null 2>&1; then
     yaourt -S obmenu-generator perl-data-dump gtk2-perl perl-linux-desktopfiles --noconfirm --needed
@@ -426,7 +432,7 @@ if ! [ "${rmob,,}" = "${yes,,}" ]; then
     sed -i '/al-kb-pipemenu/ a\
     <item label="Switch Menu">\
       <action name="Execute">\
-        <command>genmenu</command>\
+        <command>switchmenu -dynamic</command>\
       </action>\
     </item>' $MENU
   fi
@@ -437,7 +443,10 @@ fi
 
 
 
-
+clear; echo -e "${g}#######################################################################################
+#######                    Starting Application Installation                    #######
+#######################################################################################${reg}"
+sleep 1; clear
 ## Start default app install
 if ! [ "${defaults,,}" = "${no,,}" ]; then
 
@@ -1038,9 +1047,11 @@ fi
 
 
 
-
 # Window Manager Setup
 if [[ $wm == *1* ]] || [[ $wm == *2* ]] || [[ $wm == *3* ]] || [[ $wm == *4* ]]; then
+  clear; echo -e "${g}#######################################################################################
+#######                        Installing Selected WM/DE                        #######
+#######################################################################################${reg}"
 
   # XFCE
   if [[ $wm == *1* ]]; then
@@ -1134,6 +1145,9 @@ fi
 
 # Swapfile setup
 if [ "${swp,,}" = "${yes,,}" ]; then
+  clear; echo -e "${g}#######################################################################################
+#######                           Setting up Swapfile                           #######
+#######################################################################################${reg}"
   if [ "${cswp,,}" = "${yes,,}" ]; then # set custom size
     if [ -n "$size" ]; then
       if [[ $size == *G ]] || [[ $size == *M ]]; then # ensure the $size ends with G or M
@@ -1167,12 +1181,6 @@ fi
 
 
 
-if ! [ -z "${NV}" ]; then
-  clear; printf "\n  ${g}Nvidia Graphics Detected.${reg}\n\n  Want nvidia drivers installed?  [y/n]: "
-  read -r nvd
-fi
-
-
 # nvidia drivers
 if [ "${nvd,,}" = "${yes,,}" ]; then
   if [[ $wm == *2* ]] && [ "${i3ses,,}" = "${yes,,}" ]; then # if we are logging in to i3 we need to set it up is autostart
@@ -1196,7 +1204,7 @@ X-GNOME-Autostart-enabled=true' | sudo tee -a /etc/xdg/autostart/nvidia-easy-ins
   fi
 
   clear; echo -e "\n${g}  Next boot you will be promted with Nvidia Driver Installation${reg}"
-  sleep 2
+  sleep 1
 
 else
   if [ -e /etc/xdg/autostart/nvidia-easy-install.desktop ]; then
@@ -1204,8 +1212,8 @@ else
   fi
 fi
 
-clear
-read -n1 -rsp $'\n  Setup Complete!!\n\n\n  Press Any Key to Reboot or Ctrl + c to exit...'
+
+read -n1 -rsp $'\n\n  Setup Complete!!\n\n\n  Press Any Key to Reboot or Ctrl + c to exit...'
 
 systemctl reboot
 
